#!/usr/bin/env python3
import json
import subprocess
import sys

image_path = sys.argv[1]
colors = subprocess.run(
    ["matugen", "image", f"{image_path}", "--json", "hex"],
    capture_output=True,
    text=True,
)
colors_dict = json.loads(f"{colors.stdout}")
source_color = colors_dict["colors"]["dark"]["primary"]


def color_mix(color1, color2, weight):
    w = weight * 2 - 1
    w1 = (w / 2) + 0.5
    w2 = 1 - w1
    c1_r = int(color1[1:3], 16)
    c1_g = int(color1[3:5], 16)
    c1_b = int(color1[5:7], 16)
    c2_r = int(color2[1:3], 16)
    c2_g = int(color2[3:5], 16)
    c2_b = int(color2[5:7], 16)
    r = hex(int(c1_r * w1 + c2_r * w2))[2:]
    g = hex(int(c1_g * w1 + c2_g * w2))[2:]
    b = hex(int(c1_b * w1 + c2_b * w2))[2:]
    return f"#{r}{g}{b}"


base16 = {
    "base0": "#000000",
    "base1": "#ff0000",
    "base2": "#00ff00",
    "base3": "#ffff00",
    "base4": "#0000ff",
    "base5": "#ff00ff",
    "base6": "#00ffff",
    "base7": "#ffffff",
    "base8": "#000000",
    "base9": "#ff0000",
    "base10": "#00ff00",
    "base11": "#ffff00",
    "base12": "#0000ff",
    "base13": "#ff00ff",
    "base14": "#00ffff",
    "base15": "#ffffff",
}

base16_tinted = {}

for key, value in base16.items():
    weight = 0.3
    if int(key[4:]) > 7:
        weight = 0.5
    new_color = color_mix(value, source_color, weight)
    base16_tinted.update({f"{key}": f"{new_color}"})

kitty_conf = f"""
color0 {base16_tinted["base0"]} 
color1 {base16_tinted["base1"]} 
color2 {base16_tinted["base2"]} 
color3 {base16_tinted["base3"]} 
color4 {base16_tinted["base4"]} 
color5 {base16_tinted["base5"]} 
color6 {base16_tinted["base6"]} 
color7 {base16_tinted["base7"]} 
color8 {base16_tinted["base8"]} 
color9 {base16_tinted["base9"]} 
color10 {base16_tinted["base10"]} 
color11 {base16_tinted["base11"]} 
color12 {base16_tinted["base12"]} 
color13 {base16_tinted["base13"]} 
color14 {base16_tinted["base14"]} 
color15 {base16_tinted["base15"]} 
"""

kitty_path = sys.argv[2]
with open(f"{kitty_path}", "a") as target:
    target.write(kitty_conf)
