#!/usr/bin/env bash

set -xe

path=$1
kitty_path=$HOME/.config/kitty/kitty.conf

~/.cargo/bin/matugen image $path
swaybg -i $path --mode fill
$HOME/.config/scripts/base16-gen $path $kitty_path

# Reload
pkill waybar;waybar
killall dunst
rm -rf $HOME/.cache/nvim
