[config]
wallpaper = ".config/wp.jpg"

[files]
config     = {target=".config",                                                                                           }
firefox    = {target=".mozilla",                                                                                          }
dunst      = {target=".config/dunst/dunstrc",                    dest=".config", template="templates/dunstrc"             }
foot       = {target=".config/foot/foot.ini",                    dest=".config", template="templates/foot.ini"            }
gtk3css    = {target=".config/gtk-3.0/gtk.css",                  dest=".config", template="templates/gtk.css"             }
gtk4css    = {target=".config/gtk-4.0/gtk.css",                  dest=".config", template="templates/gtk.css"             }
nvim       = {target=".config/nvim/lua/plugins/colorscheme.lua", dest=".config", template="templates/nvim-colorscheme.lua"}
quickshell = {target=".config/quickshell/Colors.qml",            dest=".config", template="templates/qs-Colors.qml"       }
sway       = {target=".config/sway/config",                      dest=".config", template="templates/sway-config"         }
tmux       = {target=".config/tmux/tmux.conf",                   dest=".config", template="templates/tmux.conf"           }
tofi       = {target=".config/tofi/config",                      dest=".config", template="templates/tofi-config"         }
waybar     = {target=".config/waybar/colors.css",                dest=".config", template="templates/waybar-colors.css"   }
wofi       = {target=".config/wofi/style.css",                   dest=".config", template="templates/wofi-style.css"      }
starship   = {target=".config/starship.toml",                    dest=".config", template="templates/starship.toml"       }
