-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm';

return {
  font = wezterm.font_with_fallback({
    {
      family = "Iosevka",
      harfbuzz_features = { 'calt=0', 'clig=0', 'liga=0' }
    },
    "Symbols Nerd Font",
  }),
  font_size = 10,
  hide_tab_bar_if_only_one_tab = true,
  window_close_confirmation = "NeverPrompt",
  window_background_opacity = 0.9,
  text_background_opacity = 1.0,
  colors = {
    foreground = '#cdd6f4',
    background = '#1e1e2e',

    cursor_fg = '#1e1e2e',
    cursor_bg = '#f5e0dc',
    cursor_border = '#f5e0dc',

    selection_fg = '#cdd6f4',
    selection_bg = '#585b70',

    ansi = {
      '#45475a',
      '#f38ba8',
      '#a6e3a1',
      '#f9e2af',
      '#89b4fa',
      '#f5e0dc',
      '#94e2d5',
      '#cdd6f4',
    },
    brights = {
      '#585b70',
      '#f38ba8',
      '#a6e3a1',
      '#f9e2af',
      '#89b4fa',
      '#cba6f7',
      '#94e2d5',
      '#cdd6f4',
    },
  },
}

