#!/usr/bin/env bash

entries="󰗼 Exit\n Shutdown\n⏾ Suspend\n󰒲 Hibernate\n Reboot"

selected=$(echo -e $entries|wofi --dmenu --cache-file /dev/null | awk '{print tolower($2)}')

case $selected in
    exit)
        hyprctl dispatch exit;;
    shutdown)
        shutdown now;;
    suspend)
        systemctl suspend;;
    hibernate)
        systemctl hibernate;;
    reboot)
        reboot;;
esac
