#!/usr/bin/env bash

case $1 in
    select)
        SHAPE=$(slurp)
        grim -g "$SHAPE"
        grim -g "$SHAPE" - | wl-copy && notify-send "Screenshot saved to clipboaord" || notify-send "Invalid geometry"
        ;;
    *)
        grim
        grim - | wl-copy && notify-send "Screenshot saved to clipboaord"
        ;;
esac
