format = """
[](fg:#769ff0)\
$username\
[](fg:#769ff0 bg:#394260)\
$directory\
[](fg:#394260 bg:#212736)\
$git_branch\
$git_status\
[](fg:#212736)\
$all\
$fill\
$cmd_duration\
$time\
\n$character
"""

palette = "catppuccin_mocha"

[username]
style_user = "fg:#e3e5e5 bg:#769ff0"
style_root = "fg:yellow bg:#769ff0"
format = "[$user]($style)"
show_always = true

[directory]
style = "bold fg:#769ff0 bg:#394260"
read_only_style = "bold fg:#769ff0 bg:#394260"
format = "[ [$path]($style)[$read_only]($read_only_style)](bg:#394260)"

[git_branch]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol $branch ](bold fg:#769ff0 bg:#212736)]($style)'

[git_status]
style = "bg:#212736"
format = '[[($all_status$ahead_behind)](bold fg:#769ff0 bg:#212736)]($style)'

[line_break]
disabled = true

[python]
symbol = " "

[fill]
symbol = " "

[time]
disabled = false
time_format = "%I:%M %p" # Hour:Minute Format
style = "blue"
format = '[[$time](fg:bold crust bg:blue)]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"