format = "[](fg:#c5cd7a)$username[](fg:#c5cd7a bg:#444b04)$directory[](fg:#444b04)$all$cmd_duration\n$character"
[character]
error_symbol = "[❯](bold #ffb4ab)"
success_symbol = "[❯](bold #c5cd7a)"

[cmd_duration]
format = " took [$duration]($style)"

[directory]
format = "[[ $path]($style)[$read_only]($read_only_style)](bg:surface1)"
read_only_style = "bold fg:#e1e994 bg:#444b04"
style = "bold fg:#e1e994 bg:#444b04"

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style) "
style = "bold #e1e994"
symbol = " "

[line_break]
disabled = true

[username]
format = "[$user]($style)"
show_always = true
style_root = "bold fg:#2f3300 bg:#c5cd7a"
style_user = "bold fg:#2f3300 bg:#c5cd7a"
