format = "[](fg:#bcce80)$username[](fg:#bcce80 bg:#3e4c0c)$directory[](fg:#3e4c0c)$all$cmd_duration\n$character"
[character]
error_symbol = "[❯](bold #ffb4ab)"
success_symbol = "[❯](bold #bcce80)"

[cmd_duration]
format = " took [$duration]($style)"

[directory]
format = "[[ $path]($style)[$read_only]($read_only_style)](bg:surface1)"
read_only_style = "bold fg:#d8eb9a bg:#3e4c0c"
style = "bold fg:#d8eb9a bg:#3e4c0c"

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style) "
style = "bold #d8eb9a"
symbol = " "

[line_break]
disabled = true

[python]
symbol = " "

[username]
format = "[$user]($style)"
show_always = true
style_root = "bold fg:#293500 bg:#bcce80"
style_user = "bold fg:#293500 bg:#bcce80"
