format = "[](fg:#b2c5ff)$username[](fg:#b2c5ff bg:#304578)$directory[](fg:#304578)$all$cmd_duration\n$character"
[character]
error_symbol = "[❯](bold #ffb4ab)"
success_symbol = "[❯](bold #b2c5ff)"

[cmd_duration]
format = " took [$duration]($style)"

[directory]
format = "[[ $path]($style)[$read_only]($read_only_style)](bg:surface1)"
read_only_style = "bold fg:#dae2ff bg:#304578"
style = "bold fg:#dae2ff bg:#304578"

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style) "
style = "bold #dae2ff"
symbol = " "

[line_break]
disabled = true

[username]
format = "[$user]($style)"
show_always = true
style_root = "bold fg:#182e60 bg:#b2c5ff"
style_user = "bold fg:#182e60 bg:#b2c5ff"
