#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# workspaces
bspc monitor -d 1 2 3 4 5

# autostart
nitrogen --restore &
picom -f &
./.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nm-applet &

# configuration
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config normal_border_color "#787c99"
bspc config active_border_color "#787c99"
bspc config focused_border_color "#7aa2f7"

# window rules
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a qBittorrent desktop='^4'
